"""Render boilerplates for stdout: dump and provenance header."""

from __future__ import annotations

from typing import TYPE_CHECKING

from cobo.sources.discover import find_boilerplate

if TYPE_CHECKING:
    from pathlib import Path

    from cobo.config.schema import Source

_SHORT_SHA_LEN = 7
_COBO_HOST = "github.com/hasansezertasan/cobo"


def dump(source: Source, clone_root: Path, names: list[str], commit_sha: str) -> str:
    """Render one or more boilerplates from a source to a single string.

    Args:
        source: Resolved source.
        clone_root: Path to the source's clone on disk.
        names: One or more boilerplate names to render.
        commit_sha: Full SHA of the clone's HEAD (used in headers).

    Returns:
        Concatenated content with optional headers. A single blank line
        separates chunks; no trailing blank line is appended after the last.
    """
    chunks: list[str] = []
    for name in names:
        path = find_boilerplate(source, clone_root, name)
        repo_rel = path.relative_to(clone_root).as_posix()
        chunks.append(_render_one(source, path, repo_rel, commit_sha))
    if len(chunks) == 1:
        return chunks[0]
    stripped = [c.rstrip("\n") for c in chunks]
    return "\n\n".join(stripped) + "\n"


def _render_one(source: Source, path: Path, repo_rel_path: str, commit_sha: str) -> str:
    """Render a single boilerplate file (optionally with header).

    Returns:
        File content, optionally prefixed with a provenance header.
    """
    # Decode bytes directly rather than ``read_text`` to avoid universal-newline
    # translation, which would collapse embedded ``\r`` bytes (e.g. the macOS
    # gitignore ``Icon[\r]`` character-class trick) to ``\n`` and corrupt them.
    content = path.read_bytes().decode("utf-8")
    if not source.inject_header:
        return content
    header = build_header(
        source=source, repo_rel_path=repo_rel_path, commit_sha=commit_sha
    )
    return f"{header}\n{content}"


def build_header(source: Source, repo_rel_path: str, commit_sha: str) -> str:
    """Construct the two-line provenance header for a boilerplate.

    Line one is a fixed attribution. Line two is ``source/name@short`` followed
    by the raw URL, built from the FULL SHA and the resolved repo-relative path
    so it never 404s on nested files or abbreviated-SHA ambiguity. The URL is
    omitted for non-GitHub sources.

    Returns:
        A two-line (or, for non-GitHub sources, attribution + token) header.
    """
    short = commit_sha[:_SHORT_SHA_LEN]
    name = _stem(repo_rel_path, source.extension)
    raw_url = _raw_url(source.url, commit_sha, repo_rel_path)
    cp = source.comment_prefix
    attribution = f"{cp} Generated by cobo ({_COBO_HOST})"
    token = f"{source.name}/{name}@{short}"
    provenance = f"{cp} {token} — {raw_url}" if raw_url is not None else f"{cp} {token}"
    return f"{attribution}\n{provenance}"


def _stem(repo_rel_path: str, extension: str) -> str:
    """Return the boilerplate name (basename minus extension).

    Returns:
        The final path segment with ``extension`` removed when present.
    """
    basename = repo_rel_path.rsplit("/", 1)[-1]
    if extension and basename.endswith(extension):
        return basename[: -len(extension)]
    return basename


_GITHUB_HTTPS_PREFIX = "https://github.com/"
_GITHUB_SSH_PREFIX = "git@github.com:"


def _raw_url(url: str, sha: str, repo_rel_path: str) -> str | None:
    """Build a raw.githubusercontent URL for a file at a given SHA.

    Recognizes both HTTPS (``https://github.com/owner/repo``) and SSH
    (``git@github.com:owner/repo.git``) forms. The full SHA and the resolved
    repo-relative path are used verbatim.

    Returns:
        Raw GitHub URL, or None when the source URL is not a GitHub URL.
    """
    repo_path = _github_repo_path(url)
    if repo_path is None:
        return None
    return f"https://raw.githubusercontent.com/{repo_path}/{sha}/{repo_rel_path}"


def _github_repo_path(url: str) -> str | None:
    """Extract ``owner/repo`` from a GitHub HTTPS or SSH URL.

    Returns:
        ``owner/repo`` with any ``.git`` suffix stripped, or None when ``url``
        is not a recognized GitHub URL.
    """
    if url.startswith(_GITHUB_HTTPS_PREFIX):
        body = url[len(_GITHUB_HTTPS_PREFIX) :]
    elif url.startswith(_GITHUB_SSH_PREFIX):
        body = url[len(_GITHUB_SSH_PREFIX) :]
    else:
        return None
    return body.removesuffix(".git").rstrip("/")
