"""Tests for the dump renderer (pure string functions over fake repos)."""

from typing import TYPE_CHECKING

import pytest

from cobo.config.schema import Source
from cobo.sources.render import build_header, dump

if TYPE_CHECKING:
    from pathlib import Path

pytestmark = pytest.mark.unit


def gitignore_source() -> Source:
    """Build a gitignore-flavored Source (no header injection).

    Returns:
        A Source configured for gitignore files without header injection.
    """
    return Source(
        name="gitignore",
        url="https://github.com/github/gitignore",
        extension=".gitignore",
        multi_dump=True,
        inject_header=False,
    )


def mise_source() -> Source:
    """Build a mise-flavored Source (with header injection).

    Returns:
        A Source configured for mise TOML files with header injection.
    """
    return Source(
        name="mise",
        url="https://github.com/hasansezertasan/mise-cookbooks",
        extension=".mise.toml",
        multi_dump=False,
        inject_header=True,
        comment_prefix="#",
    )


def write_repo(tmp_path: Path, files: dict[str, str]) -> Path:
    r"""Write files into tmp_path and return it.

    Writes bytes (not ``write_text``) so platform newline translation never
    rewrites ``\\n`` to ``\\r\\n`` on Windows, keeping on-disk content exact.

    Returns:
        The tmp_path directory with files written.
    """
    for name, content in files.items():
        (tmp_path / name).write_bytes(content.encode("utf-8"))
    return tmp_path


def test_single_dump_no_header_emits_raw_content(tmp_path: Path) -> None:
    """A source with inject_header=False emits just the file content."""
    repo = write_repo(tmp_path, {"Python.gitignore": "*.pyc\n__pycache__\n"})
    out = dump(gitignore_source(), repo, ["Python"], commit_sha="abc1234")
    assert out == "*.pyc\n__pycache__\n"


def test_multi_dump_concatenates_with_blank_line_between(tmp_path: Path) -> None:
    """Two files joined with one blank line between, single trailing newline."""
    repo = write_repo(
        tmp_path,
        {
            "Python.gitignore": "*.pyc\n",
            "Node.gitignore": "node_modules/\n",
        },
    )
    out = dump(gitignore_source(), repo, ["Python", "Node"], commit_sha="abc1234")
    assert out == "*.pyc\n\nnode_modules/\n"


def test_multi_dump_three_files_uses_only_inter_chunk_separators(
    tmp_path: Path,
) -> None:
    """Three-file dump has N-1 blank-line separators, not N trailing blanks."""
    repo = write_repo(
        tmp_path,
        {
            "A.gitignore": "a\n",
            "B.gitignore": "b\n",
            "C.gitignore": "c\n",
        },
    )
    out = dump(gitignore_source(), repo, ["A", "B", "C"], commit_sha="abc1234")
    assert out == "a\n\nb\n\nc\n"


def test_dump_preserves_embedded_carriage_returns(tmp_path: Path) -> None:
    r"""Embedded ``\\r`` bytes survive a dump (no universal-newline collapse).

    The macOS gitignore uses ``Icon[\\r]`` as a character class matching a lone
    carriage return; reading via ``read_text`` would corrupt it to ``Icon[\\n]``.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "macOS.gitignore").write_bytes(b"Icon[\r]\n")
    out = dump(gitignore_source(), repo, ["macOS"], commit_sha="abc1234")
    assert out == "Icon[\r]\n"


def test_build_header_is_two_lines_with_full_sha_url() -> None:
    """Header: attribution line + `source/name@short — full-SHA url`."""
    header = build_header(
        source=mise_source(),
        repo_rel_path="python.mise.toml",
        commit_sha="0123456789abcdef0123456789abcdef01234567",
    )
    lines = header.splitlines()
    expected_line_count = 2
    assert len(lines) == expected_line_count
    assert lines[0] == "# Generated by cobo (github.com/hasansezertasan/cobo)"
    assert lines[1].startswith("# mise/python@0123456 — ")
    assert lines[1].endswith(
        "raw.githubusercontent.com/hasansezertasan/mise-cookbooks/"
        "0123456789abcdef0123456789abcdef01234567/python.mise.toml"
    )


def test_header_uses_full_sha_not_short_in_url() -> None:
    """The URL embeds the full 40-char SHA, not the 7-char token."""
    full = "a" * 40
    header = build_header(
        source=mise_source(), repo_rel_path="python.mise.toml", commit_sha=full
    )
    assert f"/{full}/" in header


def test_header_url_preserves_nested_path() -> None:
    """A nested repo path is preserved in the URL (the old 404 bug)."""
    source = Source(
        name="gitignore",
        url="https://github.com/github/gitignore",
        extension=".gitignore",
        inject_header=True,
    )
    header = build_header(
        source=source, repo_rel_path="Global/macOS.gitignore", commit_sha="b" * 40
    )
    assert header.endswith("/Global/macOS.gitignore")
    assert "gitignore/macOS@" in header  # name is the stem, not the dir


def test_header_handles_ssh_url_form() -> None:
    """SSH-form GitHub URLs still build a raw URL."""
    source = Source(
        name="mise",
        url="git@github.com:hasansezertasan/mise-cookbooks.git",
        extension=".mise.toml",
        inject_header=True,
    )
    header = build_header(
        source=source, repo_rel_path="python.mise.toml", commit_sha="c" * 40
    )
    assert "raw.githubusercontent.com/hasansezertasan/mise-cookbooks" in header
    assert ".git/" not in header


def test_header_omits_url_for_non_github_source() -> None:
    """Non-GitHub sources get only the attribution + token (no URL, no dash)."""
    source = Source(
        name="custom",
        url="https://gitlab.example.com/team/templates",
        extension=".tpl",
        inject_header=True,
    )
    header = build_header(source=source, repo_rel_path="x.tpl", commit_sha="d" * 40)
    assert "gitlab.example.com" not in header
    assert "—" not in header
    assert header.splitlines()[1] == "# custom/x@dddddddd"[: len("# custom/x@") + 7]


def test_dump_with_header_injects_two_line_header(tmp_path: Path) -> None:
    """A header-injecting source prefixes the file with the two-line header."""
    repo = write_repo(tmp_path, {"python.mise.toml": 'min_version = "2024.9.5"\n'})
    full_sha = "0123456789abcdef0123456789abcdef01234567"
    out = dump(mise_source(), repo, ["python"], commit_sha=full_sha)
    lines = out.splitlines()
    assert lines[0] == "# Generated by cobo (github.com/hasansezertasan/cobo)"
    assert lines[1].startswith("# mise/python@0123456 — ")
    assert "min_version" in out


def test_header_stem_without_matching_extension() -> None:
    """When basename lacks the source extension, the full basename is the name."""
    source = Source(
        name="licenses",
        url="https://github.com/spdx/license-list-data",
        extension=".txt",
        inject_header=True,
    )
    header = build_header(source=source, repo_rel_path="text/MIT", commit_sha="a" * 40)
    assert "licenses/MIT@" in header
